import { PersonnelType } from '../entities/employee.entity';
import { Permit, PermitStatus, PermitType } from '../entities/permit.entity';

/** Data for creating a visitor permit (plaintext idOrPhone; the repo encrypts it). */
export interface CreatePermitData {
  permitNumber: string;
  token: string; // signed HMAC permit token, generated by the use-case
  permitType: PermitType;
  status: PermitStatus;
  visitorName: string;
  idOrPhone?: string; // encrypted at rest -> *_enc + *_search_hash by the repo
  personnelType?: PersonnelType;
  host: string;
  reason?: string;
  // Scheduled-permit window (single-entry leaves these unset).
  startDate?: Date;
  endDate?: Date;
  allowedDays?: number[];
  allowedTimeFrom?: string;
  allowedTimeTo?: string;
  issuedBy?: string;
}

/**
 * The Domain owns this contract; the Data layer implements it. Out of scope for
 * this step (later): single-entry consumption (verifyAndConsume) and scan-time
 * validity — not declared here yet.
 */
export interface PermitRepository {
  /** Generate a fresh unique permit number. */
  nextPermitNumber(): Promise<string>;
  create(data: CreatePermitData): Promise<void>;
  findByPermitNumber(permitNumber: string): Promise<Permit | null>;

  /**
   * Resolve a permit by its INTERNAL database UUID (not the permit number). Used by
   * owner-status inheritance: a vehicle permit linked to a visitor permit stores the
   * permit's UUID foreign key, and the gate resolves the parent permit's validity
   * from it WITHOUT consuming it. Returns null if absent.
   */
  findById(id: string): Promise<Permit | null>;

  /**
   * Atomically consume a single-entry permit: flip active -> used (+ usedAt now).
   * Returns true if THIS call consumed it; false if it was already used. The
   * conditional update is the simple, double-spend-safe guard.
   */
  consumeSingleEntry(permitNumber: string): Promise<boolean>;
}

export const PERMIT_REPOSITORY = Symbol('PermitRepository');
