import { Injectable } from '@nestjs/common';
import { randomBytes } from 'crypto';
import { Permit } from '../../domain/entities/permit.entity';
import {
  CreatePermitData,
  PermitRepository,
} from '../../domain/repositories/permit.repository';
import { CryptoService } from '../infrastructure/crypto.service';
import { PrismaService } from '../infrastructure/prisma.service';

/**
 * Prisma implementation of PermitRepository. The visitor's id/phone is sensitive,
 * so it is AES-encrypted at rest with a deterministic search hash — exactly the
 * same treatment as the employee self_id. The signed permit token (generated by the
 * use-case) is persisted here; it is verified/consumed at the gate in a later step.
 */
@Injectable()
export class PrismaPermitRepository implements PermitRepository {
  constructor(
    private readonly prisma: PrismaService,
    private readonly crypto: CryptoService,
  ) {}

  nextPermitNumber(): Promise<string> {
    // Collision-resistant random number; the UNIQUE constraint on permit_number
    // is the backstop.
    return Promise.resolve(
      `VP-${randomBytes(5).toString('hex').toUpperCase()}`,
    );
  }

  async create(data: CreatePermitData): Promise<void> {
    await this.prisma.permit.create({
      data: {
        permitNumber: data.permitNumber,
        permitType: data.permitType,
        status: data.status,
        visitorName: data.visitorName,
        idOrPhoneEnc: data.idOrPhone
          ? this.crypto.encrypt(data.idOrPhone)
          : null,
        idOrPhoneSearchHash: data.idOrPhone
          ? this.crypto.deterministicHash(data.idOrPhone)
          : null,
        personnelType: data.personnelType ?? null,
        host: data.host,
        reason: data.reason ?? null,
        token: data.token,
        startDate: data.startDate ?? null,
        endDate: data.endDate ?? null,
        allowedDays: data.allowedDays ?? [],
        allowedTimeFrom: data.allowedTimeFrom ?? null,
        allowedTimeTo: data.allowedTimeTo ?? null,
        issuedBy: data.issuedBy ?? null,
      },
    });
  }

  async consumeSingleEntry(permitNumber: string): Promise<boolean> {
    // Conditional update is atomic at the row level: only the first scan flips an
    // active single-entry permit to used; a concurrent scan affects 0 rows.
    const result = await this.prisma.permit.updateMany({
      where: { permitNumber, permitType: 'single_entry', status: 'active' },
      data: { status: 'used', usedAt: new Date() },
    });
    return result.count === 1;
  }

  async findById(id: string): Promise<Permit | null> {
    // Keyed by the internal UUID (the foreign key a vehicle permit stores). The
    // vehicle gate flow reads the parent permit's validity from this WITHOUT
    // consuming it — no state change happens here.
    const row = await this.prisma.permit.findUnique({ where: { id } });
    if (!row) return null;

    return new Permit({
      id: row.id,
      permitNumber: row.permitNumber,
      token: row.token,
      permitType: row.permitType,
      status: row.status,
      visitorName: row.visitorName,
      idOrPhone: row.idOrPhoneEnc
        ? this.crypto.decrypt(row.idOrPhoneEnc)
        : null,
      personnelType: row.personnelType,
      host: row.host,
      reason: row.reason,
      startDate: row.startDate,
      endDate: row.endDate,
      allowedDays: row.allowedDays,
      allowedTimeFrom: row.allowedTimeFrom,
      allowedTimeTo: row.allowedTimeTo,
      expiresAt: row.expiresAt,
      usedAt: row.usedAt,
      issuedBy: row.issuedBy,
      createdAt: row.createdAt,
    });
  }

  async findByPermitNumber(permitNumber: string): Promise<Permit | null> {
    const row = await this.prisma.permit.findUnique({
      where: { permitNumber },
    });
    if (!row) return null;

    return new Permit({
      id: row.id,
      permitNumber: row.permitNumber,
      token: row.token,
      permitType: row.permitType,
      status: row.status,
      visitorName: row.visitorName,
      idOrPhone: row.idOrPhoneEnc
        ? this.crypto.decrypt(row.idOrPhoneEnc)
        : null,
      personnelType: row.personnelType,
      host: row.host,
      reason: row.reason,
      startDate: row.startDate,
      endDate: row.endDate,
      allowedDays: row.allowedDays,
      allowedTimeFrom: row.allowedTimeFrom,
      allowedTimeTo: row.allowedTimeTo,
      expiresAt: row.expiresAt,
      usedAt: row.usedAt,
      issuedBy: row.issuedBy,
      createdAt: row.createdAt,
    });
  }
}
